{{- if and .Values.secrets.create (not .Values.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "producer-app.fullname" . }}-secrets
  labels:
    {{- include "producer-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.oauth2ClientSecret }}
  oauth2-client-secret: {{ .Values.secrets.oauth2ClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.clientSecretVaultKey }}
  client-secret-vault-key: {{ .Values.secrets.clientSecretVaultKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.edcApiAuthKey }}
  edc-api-auth-key: {{ .Values.secrets.edcApiAuthKey | b64enc | quote }}
  {{- end }}
{{- end }}