{{- if and .Values.secrets.create (not .Values.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "producer-app.fullname" . }}-secrets
  labels:
    {{- include "producer-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.keycloakClientSecret }}
  keycloak-client-secret: {{ .Values.secrets.keycloakClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.vaultClientSecretKey }}
  vault-client-secret-key: {{ .Values.secrets.vaultClientSecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.edcApiAuthKey }}
  edc-api-auth-key: {{ .Values.secrets.edcApiAuthKey | b64enc | quote }}
  {{- end }}
{{- end }}