#################################################################################
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2025 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################


---
name: "Run Deployment Test"
description: "Build and publish a Docker Image to DockerHub"
inputs:
  imagename:
    required: true
    description: "list of docker image names separated by whitespace, e.g. 'edc-runtime-memory edc-runtime-other'"

  image_tag:
    required: false
    default: "latest"
    description: "docker image tag, defaults to 'latest'"

  helm_command:
    required: true
    description: "command which is executed to install the chart. must also include verification commands, such as 'helm test'"

  rootDir:
    required: true
    description: "list of directories of the modules to be dockerized, separated by whitespace, e.g. 'edc-controlplane/edc-runtime-memory edc-dataplane/edc-dataplane-memory'"

  k8sversion:
    required: false
    description: "Version of Kubernetes to use"
    default: "v1.30.0"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-java

    - uses: azure/setup-helm@v4
      with:
        version: v3.16.1
    - uses: azure/setup-kubectl@v4
      with:
        version: v1.31.1

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@b72c923563e6e80ea66e8e8c810798cc73e97e5e
      with:
        node_image: kindest/node:${{ inputs.k8sversion }}
        version: v0.29.0
        cloud_provider: true

    - name: Build docker images
      shell: bash
      working-directory: poc
      run: |-
        modules=(${{ inputs.rootDir }})
        for module in "${modules[@]}"
        do
          ./gradlew -p $module dockerize
        done

    - name: Load images into KinD
      shell: bash
      run: |
        images=(${{ inputs.imagename }})
        versioned=( "${images[@]/%/:${{ inputs.image_tag }}}" )
        versioned_images=$(IFS=' ' ; echo "${versioned[*]}")
        kind get clusters | xargs -n1 kind load docker-image $versioned_images --name

    ###################################################
    # Install the test infrastructure
    ###################################################

    - name: Install Runtime
      shell: bash
      run: ${{ inputs.helm_command }}

    - name: Print logs
      if: failure()
      shell: bash
      run: |-
        echo -e "\n=== Pod Status ==="
        kubectl get pods -n demo
        
        echo -e "\n=== Pod Logs ==="
        echo -e "\n=== consumer-app ==="
        kubectl logs deployment/demo-consumer-app -n demo
        echo -e "\n=== consumer-edc ==="
        kubectl logs deployment/demo-consumer-edc-controlplane -n demo --tail=100
        echo -e "\n=== producer-edc ==="
        kubectl logs deployment/demo-producer-edc-controlplane -n demo --tail=100

    #################
    ### Tear Down ###
    #################
    - name: Destroy the kind cluster
      if: always()
      shell: bash
      run: >-
        kind get clusters | xargs -n1 kind delete cluster --name
