{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-kafka-demo.labels" . | nindent 4 }}
data:
  realm.json: |
    {
      "realm": "kafka",
      "enabled": true,
      "clients": [
        {
          "clientId": "myclient",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "mysecret",
          "serviceAccountsEnabled": true,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "authorizationServicesEnabled": false,
          "redirectUris": []
        }
      ],
      "users": [
        {
          "username": "test-user",
          "enabled": true,
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "test-password",
              "temporary": false
            }
          ]
        }
      ]
    }
{{- end }}