#################################################################################
#  Copyright (c) 2025 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: kafka-pem
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-kafka-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDLjCCAhagAwIBAgIUZR4sZEpdrLHdS5yT/aPYGzJ6TtkwDQYJKoZIhvcNAQEL
    BQAwFDESMBAGA1UEAwwJa2Fma2EtZGV2MB4XDTI1MDkxOTA5MjQwM1oXDTM1MDkx
    NzA5MjQwM1owFDESMBAGA1UEAwwJa2Fma2EtZGV2MIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEA53h9KxP27v8D3EQMSbQxvIT7t3bceJU7+BydiYhw2kcm
    KptunDzBtBjiEVvBN5yLh5US2R4Zt+sOX1oHc2GufLZIFhp3Xg0WvNQWCCUUkszm
    eoAw8BFvLe6VypTrAQN+wyjVuro472CFDEpVJKCS42HF5oM/xIDGR5EnaQn4i9jw
    s4Zu55jD1EjAxqZD8qOIWWRDEDMHeTChy8bCppLtQqQGmIaStBuFNHOhDNBpNoV+
    hs08IM62MhgzZzah4utpCHis8uLztEIGTAJY4qoeYCxHMs2SyWS+6XEn8CnKl4mj
    UFBr83eGEWUIp5gYwbaR7WJb7u5qJxAxhkR8/ZMzLQIDAQABo3gwdjAdBgNVHQ4E
    FgQUT0oo3n3qdmdrtAd81gE3gWgUd3YwHwYDVR0jBBgwFoAUT0oo3n3qdmdrtAd8
    1gE3gWgUd3YwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
    BAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAHK17lXEN+pKNety/a72
    uUQ59pdsgxH/xU/aDBz8EzejJ2oOyFTRlcAMdbJ/bhpYUBWRYG7/oPtx7/kZAcyI
    OAFjbElTXDR6XGtn1b4eEXI0jQUPtMDRRT8L+ESuS5oNhoMeyOQ2hpT39wOI+vqM
    jdzpIdX2Voi3ZIQ9ryFHS8zMq0oZ5eaCkoCKL5wwA4Qg42qI3Hy0Hl9j3r6yyE49
    BguIxjh2Bfd3WAQBDobOl9zA1L0N0i5pBa87LFTkVEuOdAaWFDRnkd1lRIJzaP7+
    BRW7bkqKRMTLzrMGdByT7srDRanJ7PWUkhsy2NTxL4alqGuqdhvHifXZEYFejYV2
    BUE=
    -----END CERTIFICATE-----
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDLjCCAhagAwIBAgIUZR4sZEpdrLHdS5yT/aPYGzJ6TtkwDQYJKoZIhvcNAQEL
    BQAwFDESMBAGA1UEAwwJa2Fma2EtZGV2MB4XDTI1MDkxOTA5MjQwM1oXDTM1MDkx
    NzA5MjQwM1owFDESMBAGA1UEAwwJa2Fma2EtZGV2MIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEA53h9KxP27v8D3EQMSbQxvIT7t3bceJU7+BydiYhw2kcm
    KptunDzBtBjiEVvBN5yLh5US2R4Zt+sOX1oHc2GufLZIFhp3Xg0WvNQWCCUUkszm
    eoAw8BFvLe6VypTrAQN+wyjVuro472CFDEpVJKCS42HF5oM/xIDGR5EnaQn4i9jw
    s4Zu55jD1EjAxqZD8qOIWWRDEDMHeTChy8bCppLtQqQGmIaStBuFNHOhDNBpNoV+
    hs08IM62MhgzZzah4utpCHis8uLztEIGTAJY4qoeYCxHMs2SyWS+6XEn8CnKl4mj
    UFBr83eGEWUIp5gYwbaR7WJb7u5qJxAxhkR8/ZMzLQIDAQABo3gwdjAdBgNVHQ4E
    FgQUT0oo3n3qdmdrtAd81gE3gWgUd3YwHwYDVR0jBBgwFoAUT0oo3n3qdmdrtAd8
    1gE3gWgUd3YwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
    BAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAHK17lXEN+pKNety/a72
    uUQ59pdsgxH/xU/aDBz8EzejJ2oOyFTRlcAMdbJ/bhpYUBWRYG7/oPtx7/kZAcyI
    OAFjbElTXDR6XGtn1b4eEXI0jQUPtMDRRT8L+ESuS5oNhoMeyOQ2hpT39wOI+vqM
    jdzpIdX2Voi3ZIQ9ryFHS8zMq0oZ5eaCkoCKL5wwA4Qg42qI3Hy0Hl9j3r6yyE49
    BguIxjh2Bfd3WAQBDobOl9zA1L0N0i5pBa87LFTkVEuOdAaWFDRnkd1lRIJzaP7+
    BRW7bkqKRMTLzrMGdByT7srDRanJ7PWUkhsy2NTxL4alqGuqdhvHifXZEYFejYV2
    BUE=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDneH0rE/bu/wPc
    RAxJtDG8hPu3dtx4lTv4HJ2JiHDaRyYqm26cPMG0GOIRW8E3nIuHlRLZHhm36w5f
    WgdzYa58tkgWGndeDRa81BYIJRSSzOZ6gDDwEW8t7pXKlOsBA37DKNW6ujjvYIUM
    SlUkoJLjYcXmgz/EgMZHkSdpCfiL2PCzhm7nmMPUSMDGpkPyo4hZZEMQMwd5MKHL
    xsKmku1CpAaYhpK0G4U0c6EM0Gk2hX6GzTwgzrYyGDNnNqHi62kIeKzy4vO0QgZM
    Aljiqh5gLEcyzZLJZL7pcSfwKcqXiaNQUGvzd4YRZQinmBjBtpHtYlvu7monEDGG
    RHz9kzMtAgMBAAECgf9Q7E7WQKST6ZPv7dpd6iF5RwS5n1R007ejhl2NN6Y8qaMu
    QijpdlRCInDmoK1sQ86EGBn+zgcvxX3A2DjCnePitdd94sLYnrrUSVFqh4wpxnjN
    WwPA6ld0N3Um3elK8W3fzObr4S8GgTgCk/owU/MGi6gkbr5cdKjdXGHq1xGN0iAZ
    c3NXhAScWDAsQVkjI0eyFwhSGEfoSb2GJGDLo5oBfdrBrhEcgaO8VSbhJwdeyzgY
    CM6hc0KCqOYfD6xQ2UuiMICYcwPC/zHcBCWWwR0LmANJqHgnYwDdUglOHwhowbU/
    cEZfZJ0Gv4jXirozNB/cZcLHhe0xNzBe5NBQ38sCgYEA93FJNdoW/lS0jxwwsYy6
    eFLRW/CKqMWKIMpdrHnpBYMc293pT5aD6/kg3Kyl3gIg39xbUIN47bUqDD9uO43t
    ZN62hGv0X5yPpn4RHEUzNDP6KbPPEI+98NZUE8Gz9/b7i1elyeX8hUnseVrGCevr
    QDafl7mXT8iGhWXJMmjYHo8CgYEA73nMGMBf2Si7Yj3tpUw1GRU/TOvOsaUmy+lv
    FlphQt1Lf9RCPI/LzAZ8kEhpu8PqzMCaP4W3WQwtVvohqHivCe8qLACiduK/XskM
    ZFv1nvJlb1rARrIygvy8HGc3W9YSw5Qis8EziOAuBFDkc69gjwbJkaWC2WVIOXd8
    MasTcIMCgYEA6oTCYHndRRu/LcwIEp9QtG2546utn5vp+H4UHj5FLmY/2dsPH9GG
    IwaxsLUpV6sowUM2gK661IDZ41XTAjrX/rxevE8dA+l89M2TJfooN5fzx8aVwBqc
    aUCZ20fBbIj3i+98QEjr9uBDchkojYq+ItQimkjaMlHZvWDlOhPIkd0CgYEAoSee
    wJ1dIx91EoTIUy+4n9ubkKEzpHqWZC0AM9O4li2j7C8kL+s442EOHG6OsOwEK6wF
    YXAT1ZoLPPfxBJXKfW30PE5lBopK7HdxnmwAG+nVdx1kPW8X7Ow1jwuqxmOGlxUu
    UTdX/emXLhJd2rgPy9Buf1QZfUDaXMnayvXsjA8CgYAFersGHh8dMYtomBooEHzz
    jv6oDxx81PyRbosDDHjTMFGllV9lszygbdCTAMek+Q/Y/EIM1+xqyLFXEl123PjD
    YkoH43Mu07nZqJTTcC59aMOlJ0FuHuD+c5Knpvop00kNQjA8SBVu9c1RL+kPKd99
    2stWYJCdV2tjCTttVXIN/w==
    -----END PRIVATE KEY-----
