
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edc-kafka-demo.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edc-kafka-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-passwords: {{ .Values.kafka.clientPasswords | quote }}
  controller-client-secret: {{ .Values.kafka.controllerClientSecret | quote }}
  controller-password: {{ .Values.kafka.controllerPassword | quote }}
  inter-broker-client-secret: {{ .Values.kafka.interBrokerClientSecret | quote }}
  inter-broker-password: {{ .Values.kafka.interBrokerPassword | quote }}
