#################################################################################
#  Copyright (c) 2025 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "edc-kafka-demo.fullname" . }}-test-consumer-subscribe"
  labels:
    {{- include "edc-kafka-demo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: consumer-subscribe-test
      image: curlimages/curl:8.4.0
      command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Testing consumer-app /api/subscribe endpoint..."
          
          # Wait for consumer-app service to be ready
          echo "Waiting for consumer-app service to be available..."
          until nc -z {{ .Release.Name }}-consumer-app 8080; do
            echo "Waiting for {{ .Release.Name }}-consumer-app:8080..."
            sleep 5
          done
          
          echo "Making POST request to /api/subscribe with assetId=kafka-forecast-asset..."
          
          # Make POST request to the subscribe endpoint
          RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" \
            -X POST \
            "http://{{ .Release.Name }}-consumer-app:8080/api/subscribe?assetId=kafka-forecast-asset" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json")
          
          # Extract HTTP code and response body
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1 | cut -d: -f2)
          RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status Code: $HTTP_CODE"
          echo "Response Body: $RESPONSE_BODY"
          
          # Check if HTTP status is successful (2xx)
          if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
            echo "ERROR: HTTP request failed with status code $HTTP_CODE"
            exit 1
          fi
          
          # Check if response contains recordCount field
          if ! echo "$RESPONSE_BODY" | grep -q "recordCount"; then
            echo "ERROR: Response does not contain 'recordCount' field"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi
          
          # Extract recordCount value using basic text processing
          RECORD_COUNT=$(echo "$RESPONSE_BODY" | grep -o '"recordCount"[[:space:]]*:[[:space:]]*[0-9]*' | grep -o '[0-9]*$' || echo "0")
          
          echo "Record Count: $RECORD_COUNT"
          
          # Validate that recordCount is greater than 0
          if [ "$RECORD_COUNT" -le 0 ]; then
            echo "ERROR: recordCount ($RECORD_COUNT) is not greater than 0"
            exit 1
          fi
          
          echo "SUCCESS: Subscribe endpoint test passed with recordCount=$RECORD_COUNT"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL