server:
  port: 8080

spring:
  application:
    name: kafka-consumer

logging:
  level:
    root: WARN
    org.eclipse.tractusx.edc.kafka.consumer: INFO
    org.springframework: INFO
    org.apache.kafka: WARN