@startuml
/'
SPDX-License-Identifier: CC-BY-4.0
SPDX-FileCopyrightText: (c) 2025 Cofinity-X GmbH
'/
box "Consumer cluster" #LightYellow
    participant "Control Plane" as ConsumerCP
end box

box "Provider cluster" #LightBlue
    participant "Control Plane"  as ProviderCP
    participant "Kafka Extension" as ProviderKE
    participant "Data Plane"  as ProviderDP
    participant "OAuth Service" as OAuth2
    participant "Kafka Service" as Kafka
end box

== Data suspending/terminating ==
ProviderCP -> ProviderKE : Suspend/terminate message
ProviderKE -> ProviderDP : Revoke token
ProviderDP -> OAuth2 : Revoke token
Kafka -> Kafka : Stop Polling for outdated token
ProviderDP <-- OAuth2 : Token revoked
ProviderKE <-- ProviderDP : Token revoked
ProviderCP <-- ProviderKE : Transfer suspended/terminated
@enduml