#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
name: helm-chart-release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure gh-pages branch exists (no checkout)
        shell: bash
        run: |
          set -euo pipefail
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            EMPTY_TREE="$(git hash-object -t tree /dev/null)"
            COMMIT="$(printf "Initialize gh-pages branch\n" | git commit-tree "$EMPTY_TREE")"
            git update-ref refs/heads/gh-pages "$COMMIT"
            git push origin refs/heads/gh-pages
          fi

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Configure Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add eclipse-tractusx https://eclipse-tractusx.github.io/charts/dev
          helm repo update

      - name: Build chart dependencies
        run: |
          helm dependency build charts/edc-kafka-demo || true
          helm dependency build charts/tractusx-edc-kafka || true

      - name: Package only allowed charts
        run: |
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package charts/edc-kafka-demo --destination .cr-release-packages
          helm package charts/tractusx-edc-kafka --destination .cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0 # using 1.5.0 version because of https://github.com/helm/chart-releaser-action/issues/171
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts
          skip_packaging: true
          config: ./.github/configs/cr-config.yml